[server]
port = 8502
address = "localhost"
headless = true

[browser]
serverAddress = "localhost"
serverPort = 8502

[theme]
primaryColor = "#2439f7"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1c24"
textColor = "#fafafa" 